# Generated by Django 4.2.1 on 2023-07-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('num_available', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
