# Generated by Django 4.2.1 on 2023-07-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_book_reserved_by_book_reserved_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reserved_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reserved_on',
        ),
    ]
